GET http://localhost:3001/api/notes
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "This is a testing content string", 
    "important": true
}

# this file contains docs for formatting this .rest file: 
# https://github.com/Huachao/vscode-restclient/blob/master/README.md#usage
# multiple requests are separated by double hash: ###